### ISSUE TITLE
Error: Invalid hiscores format

### ISSUE THREAD

**Issue by Nikkezz** [maxswa/osrs-json-hiscores#69]
Getting this error, maybe because of system update today in osrs?
I tried to update the osrs-json-hiscores package.

```
Error: Invalid hiscores format
    at parseStats (C:\Users\x\Documents\GitHub\x\x\node_modules\osrs-json-hiscores\lib\hiscores.js:101:15)
    at Object.<anonymous> (C:\Users\x\Documents\GitHub\x\x\node_modules\osrs-json-hiscores\lib\hiscores.js:222:35)
    at step (C:\Users\x\Documents\GitHub\x\x\node_modules\osrs-json-hiscores\lib\hiscores.js:44:23)
    at Object.next (C:\Users\x\Documents\GitHub\x\x\node_modules\osrs-json-hiscores\lib\hiscores.js:25:53)
    at fulfilled (C:\Users\x\Documents\GitHub\x\x\node_modules\osrs-json-hiscores\lib\hiscores.js:16:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by maxswa** [comment]
Looks like they added the wilderness boss variants to the hiscores. I'll get a fix in for this ASAP.

**Comment by maxswa** [comment]
The latest version fixes this issue by adding support for the wilderness boss variants `osrs-json-hiscores@2.13.0`
